spring:
  application:
    name: service-b

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: '1.0'
  otlp:
    tracing:
      endpoint: http://simplest-collector:4318/v1/traces